import {MenuDiario } from './MenuDiario';

export const MENU: MenuDiario[] = [
  { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'LUNES' },
   { comidas: [
    {nombre: "arrozconpollo",
    descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
    descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'MARTES' },
   { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'MIERCOLES' },
   { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'JUEVES' },
   { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'VIERNES' },
   { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'SABADO' },
   { comidas: [
    {nombre: "arrozconleche",
    descripcion: "arroz con leche",
    numeroRaciones: 50,
    comidaTipo: "DESAYUNO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arrozconpollo",
     descripcion: "arroz con pollo",
    numeroRaciones: 50,
    comidaTipo: "ALMUERZO",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
    {nombre: "arroz con pure",
    descripcion: "arroz con pollo",
    numeroRaciones: 5,
    comidaTipo: "CENA",
    dia:"",
    inicioReserva: "5",
    finReserva: "5"},
  ],
   dia: 'DOMINGO' },
   
];